version: "3.5"

services:

  mysql-master:
    container_name: mysql-master
    image: mysql:5.7.26
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=customerdb
    volumes:
      - ./mysql/master.sql:/docker-entrypoint-initdb.d/master.sql
    command: ["--server-id=1", "--log-bin=mysql-bin.log", "--relay_log_info_repository=TABLE",
              "--master-info-repository=TABLE", "--gtid-mode=on", "--enforce-gtid-consistency"]
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 10s

  mysql-slave-1:
    container_name: mysql-slave-1
    image: mysql:5.7.26
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=customerdb
    volumes:
      - ./mysql/slave.sql:/docker-entrypoint-initdb.d/slave.sql
    command: ["mysqld", "--server-id=2", "--enforce-gtid-consistency=ON", "--log-slave-updates=ON", "--read_only=TRUE",
              "--skip-log-bin", "--skip-log-slave-updates", "--gtid-mode=ON"]
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 10s

  mysql-slave-2:
    container_name: mysql-slave-2
    image: mysql:5.7.26
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=customerdb
    volumes:
      - ./mysql/slave.sql:/docker-entrypoint-initdb.d/slave.sql
    command: ["mysqld", "--server-id=2", "--enforce-gtid-consistency=ON", "--log-slave-updates=ON", "--read_only=TRUE",
              "--skip-log-bin", "--skip-log-slave-updates", "--gtid-mode=ON"]
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 10s

  proxysql:
    container_name: proxysql
    image: proxysql/proxysql:2.0.4
    restart: unless-stopped
    ports:
      - "6033:6033"
      - "6032:6032"
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
