version: "3.5"

services:

  mysql-master:
    container_name: mysql-master
    image: mysql:5.7.26
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=customerdb
    command: ["mysqld", "--server-id=1", "--log-bin=mysql-bin.log", "--enforce-gtid-consistency=ON",
              "--log-slave-updates=ON", "--gtid-mode=ON"]
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 10s

  mysql-slave-1:
    container_name: mysql-slave-1
    image: mysql:5.7.26
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=customerdb
    command: ["mysqld", "--server-id=2", "--enforce-gtid-consistency=ON", "--log-slave-updates=ON", "--gtid-mode=ON"]
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 10s

  mysql-slave-2:
    container_name: mysql-slave-2
    image: mysql:5.7.26
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=customerdb
    command: ["mysqld", "--server-id=3", "--enforce-gtid-consistency=ON", "--log-slave-updates=ON", "--gtid-mode=ON"]
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 10s
